### ISSUE TITLE
Add support for per team deployments of stac-fastapi components (like stac-fastapi-pgstac, stac-fastapi-elasticsearch backend,...)

### ISSUE THREAD

**Issue by kalxas** [EOEPCA/resource-discovery#27]

**Comment by achtsnits** [comment]
**Requirements**

Enable teams to deploy individual ("private") required components for their data management tasks via Kubernetes independently (=in self-service mode), without operational overhead:

- deploy catalogue/search components with minimal friction following a sample recipe
- rely on a managed database inside the Datalab (i.e. no friction in selecting proper storage class and outsource topics like automated backups)
- tolerate credential rotation without downtime or manual fixes

Typical components (e.g., STAC APIs, pycsw):

- need a dedicated database (for Terrabyte we also need to make the database available outside the Kubernetes cluster → Layer 4)
- connect to the workspace’s object-storage of the team
- should be deployable without being required to tweak with credentials or operational concerns

**Example: Team-Scoped Datalab with Database**
(following concept presented in meeting 11.11.2025)

Note: when you create a Workspace through the workspace-api, you internally automatically create a `Storage` as well as a `Datalab` CR (both established via respective Crossplane composition)

```yaml
apiVersion: pkg.internal/v1beta1
kind: Datalab
metadata:
  name: ws-alice
spec:
  users: [ws-alice]
  secretName: jane
  sessions: [default]
  vcluster: true
  quota:
    memory: 4Gi
    storage: 10Gi
    budget: x-large
  security:
    kubernetesRole: admin
  databases:               <-------- NEW
    - name: analytics
      storage: 3Gi
```
